import os
import smtplib
import ssl
from email.message import EmailMessage
from email.utils import formatdate
import logging
from typing import List, Dict, Any

log = logging.getLogger("email_service")

def _get_credentials():
    sender_email = os.getenv("GMAIL_SENDER_EMAIL")
    app_password = os.getenv("GMAIL_APP_PASSWORD")
    return sender_email, app_password

def _send_email(subject: str, html_content: str, to_emails: List[str]) -> Dict[str, Any]:
    if not to_emails:
        log.info("No recipients provided. Skipping email send.")
        return {"error": "No recipients", "status": "skipped"}

    sender_email, app_password = _get_credentials()
    if not sender_email or not app_password:
        log.error("Gmail credentials not configured in environment variables.")
        return {"error": "Credentials missing", "status": "error"}

    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = f"GAM 360 Live <{sender_email}>"
    msg['To'] = ", ".join(to_emails)
    msg['Date'] = formatdate(localtime=True)
    
    msg.set_content("Please enable HTML to view this email.")
    msg.add_alternative(html_content, subtype='html')

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(sender_email, app_password)
            server.send_message(msg)
            
        log.info(f"Email sent successfully to {len(to_emails)} recipients: {subject}")
        return {"status": "success"}
    except Exception as e:
        log.error(f"Failed to send email: {e}")
        return {"error": str(e), "status": "error"}

def send_alert_email(alert: Dict[str, Any], to_emails: List[str]) -> Dict[str, Any]:
    if not to_emails:
        return {"error": "No recipients", "status": "skipped"}
        
    severity = alert.get("severity", "warning").lower()
    title = alert.get("title", "Unknown Alert")
    metric = alert.get("metric", "Unknown Metric")
    value = alert.get("value", "")
    
    prefix = "🔴 CRITICAL:" if severity == "critical" else "🟠 WARNING:"
    subject = f"{prefix} {title}"
    
    color = "#ef4444" if severity == "critical" else "#f59e0b"
    bg_color = "#fef2f2" if severity == "critical" else "#fffbeb"
    
    html = f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; background-color: #ffffff;">
        <h2 style="color: {color}; margin-top: 0; display: flex; align-items: center;">
            <span style="background-color: {bg_color}; padding: 8px 12px; border-radius: 6px; font-size: 18px;">
                {prefix} GAM 360 Live Alert
            </span>
        </h2>
        
        <div style="padding: 20px 0; border-top: 1px solid #e5e7eb; border-bottom: 1px solid #e5e7eb; margin: 20px 0;">
            <h3 style="margin: 0 0 10px 0; color: #111827; font-size: 20px;">{title}</h3>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                <tr>
                    <td style="padding: 8px 0; color: #6b7280; width: 100px;">Metric:</td>
                    <td style="padding: 8px 0; color: #111827; font-weight: 600;">{metric}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #6b7280;">Value:</td>
                    <td style="padding: 8px 0; color: #111827; font-weight: 600;">{value}</td>
                </tr>
                <tr>
                    <td style="padding: 8px 0; color: #6b7280;">Severity:</td>
                    <td style="padding: 8px 0; color: {color}; font-weight: 600; text-transform: capitalize;">{severity}</td>
                </tr>
            </table>
        </div>
        
        <p style="color: #6b7280; font-size: 13px; margin: 0;">
            This is an automated alert generated by the GAM 360 Live Reporting Engine based on real-time data.
        </p>
    </div>
    """
    
    return _send_email(subject, html, to_emails)

def send_daily_report_email(report_data: Dict[str, Any], to_emails: List[str]) -> Dict[str, Any]:
    if not to_emails:
        return {"error": "No recipients", "status": "skipped"}
        
    summary = report_data.get("executive_summary", {})
    period = summary.get("period", "Unknown Period")
    
    subject = f"📊 GAM 360 Live Executive Report: {period}"
    
    # Extract metrics safely
    rev = summary.get('total_revenue_usd', 0)
    imp = summary.get('total_impressions', 0)
    ecpm = summary.get('average_ecpm', 0)
    ctr = summary.get('average_ctr', 0)
    fill = summary.get('average_fill_rate', 0)
    
    # Top apps table
    apps = report_data.get("top_apps", [])
    apps_rows = ""
    for idx, app in enumerate(apps):
        a_name = app.get("ad_unit_name", "")
        a_rev = app.get("ad_server_cpm_and_cpc_revenue", 0)
        a_imp = app.get("ad_server_impressions", 0)
        apps_rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #374151; color: #f3f4f6;">{idx+1}. {a_name}</td>
            <td style="padding: 10px; border-bottom: 1px solid #374151; text-align: right; color: #f3f4f6;">${a_rev:,.2f}</td>
            <td style="padding: 10px; border-bottom: 1px solid #374151; text-align: right; color: #9ca3af;">{a_imp:,}</td>
        </tr>
        """
        
    # Anomalies
    anomalies = report_data.get("anomalies", [])
    anomalies_html = ""
    if anomalies:
        anomalies_rows = ""
        for a in anomalies:
            desc = a.get("description", "")
            sev = a.get("severity", "")
            color = "#ef4444" if sev == "High" else "#f59e0b" if sev == "Medium" else "#3b82f6"
            anomalies_rows += f"""
            <div style="margin-bottom: 8px; padding-left: 12px; border-left: 3px solid {color}; color: #d1d5db;">
                {desc}
            </div>
            """
        anomalies_html = f"""
        <div style="margin-top: 30px; background-color: #1f2937; padding: 20px; border-radius: 8px;">
            <h3 style="margin-top: 0; color: #f3f4f6; font-size: 18px;">⚠️ Detected Anomalies</h3>
            {anomalies_rows}
        </div>
        """

    # Recommendations
    recs = report_data.get("recommendations", [])
    recs_html = ""
    if recs:
        recs_rows = ""
        for r in recs:
            title = r.get("title", "")
            desc = r.get("description", "")
            recs_rows += f"""
            <div style="margin-bottom: 12px; color: #d1d5db;">
                <strong style="color: #60a5fa;">• {title}:</strong> {desc}
            </div>
            """
        recs_html = f"""
        <div style="margin-top: 20px; background-color: #1f2937; padding: 20px; border-radius: 8px;">
            <h3 style="margin-top: 0; color: #f3f4f6; font-size: 18px;">💡 Recommendations</h3>
            {recs_rows}
        </div>
        """

    html = f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 650px; margin: 0 auto; background-color: #111827; color: #f3f4f6; padding: 30px; border-radius: 12px;">
        
        <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #ffffff; margin-bottom: 5px; font-size: 24px;">GAM 360 Live Executive Report</h1>
            <p style="color: #9ca3af; margin-top: 0;">Period: {period}</p>
        </div>
        
        <div style="background-color: #1f2937; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
            <h3 style="margin-top: 0; color: #f3f4f6; font-size: 18px; border-bottom: 1px solid #374151; padding-bottom: 10px;">Executive Summary</h3>
            <div style="display: flex; flex-wrap: wrap; margin-top: 15px;">
                <div style="flex: 1; min-width: 120px; margin-bottom: 15px;">
                    <div style="color: #9ca3af; font-size: 12px; text-transform: uppercase;">Total Revenue</div>
                    <div style="color: #10b981; font-size: 24px; font-weight: 600;">${rev:,.2f}</div>
                </div>
                <div style="flex: 1; min-width: 120px; margin-bottom: 15px;">
                    <div style="color: #9ca3af; font-size: 12px; text-transform: uppercase;">Impressions</div>
                    <div style="color: #f3f4f6; font-size: 24px; font-weight: 600;">{imp:,}</div>
                </div>
                <div style="flex: 1; min-width: 120px; margin-bottom: 15px;">
                    <div style="color: #9ca3af; font-size: 12px; text-transform: uppercase;">Avg eCPM</div>
                    <div style="color: #f3f4f6; font-size: 24px; font-weight: 600;">${ecpm:,.2f}</div>
                </div>
            </div>
            <div style="display: flex; flex-wrap: wrap;">
                <div style="flex: 1; min-width: 120px;">
                    <div style="color: #9ca3af; font-size: 12px; text-transform: uppercase;">Fill Rate</div>
                    <div style="color: #f3f4f6; font-size: 18px;">{fill:,.1f}%</div>
                </div>
                <div style="flex: 1; min-width: 120px;">
                    <div style="color: #9ca3af; font-size: 12px; text-transform: uppercase;">CTR</div>
                    <div style="color: #f3f4f6; font-size: 18px;">{ctr:,.2f}%</div>
                </div>
                <div style="flex: 1; min-width: 120px;">
                </div>
            </div>
        </div>

        <div style="background-color: #1f2937; padding: 20px; border-radius: 8px;">
            <h3 style="margin-top: 0; color: #f3f4f6; font-size: 18px; border-bottom: 1px solid #374151; padding-bottom: 10px;">Top Performing Applications</h3>
            <table style="width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px;">
                <thead>
                    <tr>
                        <th style="text-align: left; padding: 10px; color: #9ca3af; border-bottom: 1px solid #374151;">Application</th>
                        <th style="text-align: right; padding: 10px; color: #9ca3af; border-bottom: 1px solid #374151;">Revenue</th>
                        <th style="text-align: right; padding: 10px; color: #9ca3af; border-bottom: 1px solid #374151;">Impressions</th>
                    </tr>
                </thead>
                <tbody>
                    {apps_rows}
                </tbody>
            </table>
        </div>
        
        {anomalies_html}
        
        {recs_html}

        <div style="margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px;">
            <p>Generated automatically by GAM 360 Live Reporting Platform.</p>
            <p>You received this because you are subscribed to Daily Reports.</p>
        </div>
    </div>
    """
    
    return _send_email(subject, html, to_emails)
